### ISSUE TITLE
No apparent way to specify service name

### ISSUE THREAD

**Issue by majelbstoat** [googleapis/nodejs-error-reporting#71] opened 2018-03-11 21:16 UTC
This may be either a feature or documentation request.

I'm logging and reporting to Stackdriver from a nodeJS express app running on GKE, following the documentation at https://cloud.google.com/error-reporting/docs/setup/nodejs.

```
import ErrorReporting from '@google-cloud/error-reporting'
const errors = ErrorReporting()

...

express().use(errors.express)
```

Errors are being reported, which is a great start :) However, they are appearing in the `gke_instances` section of Stackdriver Error Reporting rather than `my-service-name` as I would like, even though the logging goes to 
`logName="projects/my-project-id/logs/my-service-name"` in Stackdriver Logging.

<img width="690" alt="screenshot 2018-03-11 14 14 13" src="https://user-images.githubusercontent.com/425787/37258514-8516c1d0-2536-11e8-8314-be3fc43dfd97.png">

Having spelunked the code, and getting a similar approach to work for Golang Stackdriver Error Reporting, I tried:

```
const errors = ErrorReporting({
  serviceContext: {
    service: 'my-service-name',
  },
})
```

However, reporting still happens to the `gke_instances` section. Either there is no current way to send the error reports with the right service name, or the documentation to do so is hard to find or unclear. (Or I didn't look hard enough, in which case, sorry 😬) 

(I know I'm using beta software, and I appreciate the extent to which error reporting is already supported, thank you 🙇) 

#### Environment details

  - OS: Linux
  - Node.js version: 8.9.4
  - npm version: 5.6.0
  - @google-cloud/error-reporting version: 0.2.3

**Comment by DominicKramer** [comment] 2018-03-13 16:55
Thanks for the feedback.  I agree having the errors reported under the `gke_instances` sections is confusing.  I will need to investigate whether this is the intended behavior, and I will let you know of any updates.  Thanks.

**Comment by lostpebble** [comment] 2018-05-14 16:31
Any update on this? I have many Node.js services running in my Kubernetes cluster now, and having them all fall under the same sort of service, as `gke_instances` is a detriment to quickly knowing where an error is actually occurring.

**Comment by DominicKramer** [comment] 2018-05-14 22:40
Sorry for the delay.  I'm still working on this and I hope to have a solution soon.  Thanks

**Comment by DominicKramer** [comment] 2018-05-18 18:14
I've done some experimenting, and it looks like if my (TypeScript) code is:
```ts
import {ErrorReporting} from '@google-cloud/error-reporting';
const errors = new ErrorReporting({
  ignoreEnvironmentCheck: true,
  serviceContext: {
    service: 'some-service',
    version: 'some-version'
  }
});

import * as express from 'express';

const app = express();
app.get('/',  ...);
app.use(errors.express);
app.listen(...);
```
then errors are reported under `gke_instances` and `some-service`.

I think it is being displayed under `gke_instances` since the stack trace of the error reported is observed in standard error and is reported automatically, but its associated service is unknown.

It is reported under `some-service` since `app.use(errors.express)` occurs under `app.get`, `app.post`, etc. and so the `errors.express` plugin handles the error and knows the associated service.

If, on the other hand, I have `app.use(errors.express)` above `app.get`, `app.post`, etc. as in:
```ts
import {ErrorReporting} from '@google-cloud/error-reporting';
const errors = new ErrorReporting({
  ignoreEnvironmentCheck: true,
  serviceContext: {
    service: 'some-service',
    version: 'some-version'
  }
});

import * as express from 'express';

const app = express();
app.use(errors.express);
app.get('/',  ...);
app.listen(...);
```
then the error is reported only under `gke_instances` (for the same reason I described above).  In this case, it looks like the `errors.express` plugin is not invoked at all, which would explain why the error isn't being reported for `some-service`.

Also, make sure you have `NODE_ENV` set to `production` or  set the `ignoreEnvironmentCheck` configuration option to `true`.  Otherwise, the error-reporting plugin won't be enabled.

I would like to know if any of these addresses the issue you were seeing.  If not, let me know, and I will dig deeper.  Thanks.

**Comment by majelbstoat** [comment] 2018-05-18 18:56
Thank you, I will try and check these out today.

**Comment by majelbstoat** [comment] 2018-05-19 01:56
That did it! Putting `errors.express` last in the chain has them coming through in both places, as you describe, thank you!

Do you have a sense of whether it's possible to only have the error be reported through error-reporting, or else how to associate a service-name with the stderr reporting? It appears the latter is a function of stackdriver logging inside GKE. Would love to not have duplicates. (But this alone is a great improvement, thanks.)

**Comment by DominicKramer** [comment] 2018-05-21 17:17
I'm closing this issue since it sounds like it is resolved.

I agree that addressing the duplicate bug reporting is important, and I'm opened a new issue #130 to track that specific issue and its associated discussion.

**Closed by DominicKramer** 2018-05-21 17:17 UTC
Labels: bug

**Comment by lostpebble** [comment] 2019-10-11 13:16
I have to report back that this is still a problem. I only see `gke_instances` in my error reporting, and its getting very frustrating now as I often have no idea where an error is originating in my cluster.

Others also struggling with this: https://stackoverflow.com/questions/57315784/stackdriver-error-reporting-for-gke-cluster

I have to always go into the logs of the error to see the actual resource labels. I don't understand why those labels are not automatically integrated with Google's error reporting too- would make life a hell of a lot easier.

**Comment by richardscarrott** [comment] 2020-04-17 08:28
yeah, if you're inside a VM / K8 cluster on GCP I don't think there's any need for this nodejs package as it's automatically put into stackdriver logging and stackdriver error reporting from stdout and stderr which is great.

It is incredibly frustrating to not get the service name in error reporting however. @lostpebble did you find a solution to this at all?

Also,  re: putting `errors.express` last in the chain; that is what you want to do if using this library -- putting it first in the chain is no different to not putting it in the middleware stack at all, e.g.

```js
const express = require('express');
const app = express();

// ASIDE: The arity must be 4, otherwise it's not an *error* middleware.
app.use((err, req, res, next) => {
  // This this will not get hit
  console.error('Err 1', err.message);
  res.sendStatus(500);
});

app.get('/foo', (req, res) => {
  throw new Error('b0rked');
});

// ASIDE: The arity must be 4, otherwise it's not an *error* middleware.
app.use((err, req, res, next) => {
  console.error('Err 2', err.message);
  res.sendStatus(500);
});

app.listen(3000);
```

**Comment by richardscarrott** [comment] 2020-04-20 11:27
The solution is hidden away here https://issuetracker.google.com/issues/62828996#comment10

In short, you can define `serviceContext` on the object logged to stdout / stderr, e.g.

```js
console.error({
  severity: 500,
  serviceContext: {
    service: 'my-service-name'
  }
});
```
