### ISSUE TITLE
Error's stack trace not being fully parsed

### ISSUE THREAD

**Issue by majelbstoat** [googleapis/nodejs-error-reporting#129] opened 2018-05-19 19:41 UTC
I have an error with a full stack trace that, when reported, does not include the full stack trace.

The error, when printed, looks like this.

```
Error: 6 ALREADY_EXISTS: User "faa85d666e773751" already has a position for question "42".
     at new GraphQLError (/usr/src/service/dist/bundle.js:1756:28)
     at Function.__dirname../app/lib/error.ts.GraphQLError.fromGRPC (/usr/src/service/dist/bundle.js:1776:16)
     at ContentService.<anonymous> (/usr/src/service/dist/bundle.js:276:47)
     at step (/usr/src/service/dist/bundle.js:119:23)
     at Object.throw (/usr/src/service/dist/bundle.js:100:53)
     at rejected (/usr/src/service/dist/bundle.js:92:65)
     at propagateAslWrapper (/usr/src/service/node_modules/async-listener/index.js:502:23)
     at /usr/src/service/node_modules/async-listener/index.js:539:70
     at <anonymous>
```

I'm reporting using:

```errors.report(err)```

The error is reported successfully, under the correct service, however, there is no stacktrace associated with the report:

<img width="582" alt="screenshot 2018-05-19 12 16 58" src="https://user-images.githubusercontent.com/425787/40272186-99a990c4-5b5e-11e8-9035-bb6e2bab68ab.png">

The third line of the stacktrace is a little weird, (I guess it's generated from the typescript compilation somehow), and raw looks like this:

<img width="585" alt="screenshot 2018-05-19 12 40 40" src="https://user-images.githubusercontent.com/425787/40272449-e7e67d1c-5b61-11e8-8fcb-41304f7f793d.png">

but I don't know if that's the issue.

#### Environment details

  - OS: Alpine latest
  - Node.js version: 8.9.4
  - @google-cloud/error-reporting version: 0.4.0

**Comment by DominicKramer** [comment] 2018-06-13 18:40
On further investigation, it looks like the issue you are seeing is an issue with Error Reporting service itself and not this specific library.  The team responsible for the Error Reporting service is investigating this issue, and I will update this thread with any additional information I receive.

Further, it looks like once the issue has been addressed in the service, the stack traces in question should be parsed correctly without you needing to use an updated version of the `@google-cloud/error-reporting` library.

**Comment by DominicKramer** [comment] 2018-07-16 18:54
I've talked with the Error Reporting team, and confirmed the issue is with the line:
```
     at Function.__dirname../app/lib/error.ts.GraphQLError.fromGRPC (/usr/src/service/dist/bundle.js:1776:16)
```
Unfortunately, it looks like the line is not a properly formatted Node.js stack trace and, as such, is something that the Error Reporting Service cannot parse and won't be able to fix.

Thus, at this point, I will close this issue, since it looks like the best approach is to determine why the code that is generating the stack trace is generating an invalid stack trace, which is outside the scope of this repo.

**Closed by DominicKramer** 2018-07-16 18:54 UTC
Labels: priority: p2, status: will not fix, type: bug
