### ISSUE TITLE
Error Reporting and reportUnhandledRejections - what am I doing wrong?

### ISSUE THREAD

**Issue by derrickrc** [googleapis/nodejs-error-reporting#548] opened 2021-03-30 00:51 UTC
I have a Node.js Cloud Function and am trying to be alerted to unhandled rejections. Error Reporting overall seems to be working as I can get alerted if I manually throw a `console.error('error')`. 

If I throw an unhandled rejection and cause a crash in my `index.js` entry point, the error shows up in Error Reporting (although I don't receive a notification for some reason). This also shows up as log level "critical": 

![Screen Shot 2021-03-29 at 5 45 12 PM](https://user-images.githubusercontent.com/46724607/112917222-18895380-90b7-11eb-91dd-7363ab2484f6.png)

If I throw an identical unhandled rejection in a different .js file in the same Cloud Function (which is being imported by `index.js`), it does not show up as log level "critical" and the error is never reported in Error Reporting:

![Screen Shot 2021-03-29 at 5 45 04 PM](https://user-images.githubusercontent.com/46724607/112917278-2c34ba00-90b7-11eb-8ece-330710df5f47.png)

What is the correct way to ensure I capture all unhandled rejections across my entire Cloud Function (and ensure I receive alerts)? Do I need to initialize an instance of error reporting in every single .js file within my cloud function? This is how I am initializing Error Reporting in my `index.js` entry point: 

```
const {ErrorReporting} = require('@google-cloud/error-reporting');

      const errors = new ErrorReporting({
        reportUnhandledRejections: true
      });
```

**Comment by nicoleczhu** [comment] 2021-04-05 20:04
@derrickrc have you tried initializing a new error reporting client in each js file? the reason that's important is that errors need to know the relative location of the error in your source code. See more info in formatting requirements: https://cloud.google.com/error-reporting/docs/formatting-error-messages

Aside, another reason could be that your functions are finished with execution (thus cpu is ramped down) before the error is emitted. One way around it is to synchronously emit error logs.

**Comment by derrickrc** [comment] 2021-04-05 20:10
@nicoleczhu thanks Nicole - I don't believe it's because my functions have already terminated. I have not tried initializing in each .js file, but was hoping to avoid doing that if possible. Is there any way to initialize it once across the entire Cloud Function?  If not, I guess I'll do it individually for each .js file.

**Comment by nicoleczhu** [comment] 2021-04-05 20:28
Can you try it in each file? ​Can you provide a longer snippet of your implementation? 

Also you actually do not need this library for errors to be picked up by error reporting. You can console.log to STDOUT in [this format](https://cloud.google.com/error-reporting/docs/formatting-error-messages#log-entry-examples). I'd do this if I were you, because of the above mentioned race condition. Even if you aren't experiencing that now, you might under greater load. It'll also make for a lighter implementation/less dependencies, no need to include it in each file, etc.

Here's an example for how to write [structured logs to stdout](https://cloud.google.com/functions/docs/monitoring/logging#writing_structured_logs).

**Comment by derrickrc** [comment] 2021-04-05 21:01
Thank you @nicoleczhu . Here is the main snippet, I am still relatively new to node.js so please advise if this isn't best practice. For example, `deleteProduct` and `updateInventory` are methods I have written that live in other .js files and are being imported within this main `index.js` file. 

Regarding using STDOUT, does that mean though that I would have to `try / catch ` and log it in the `catch`? I guess what I am hoping to be notified of any exceptions I might have not planned for. 

```
exports.myFunction = async (req, res) => {
    // if it's a closed order 
    if (json.hasOwnProperty('closed_at')) {
     let awaiter = new Promise((resolve) => {
        // get order object from orders directory
        await ordersRef.once("value", async function(snapshot) {
            var orderResponseObj = snapshot.val();

            await deleteRef.once("value", async function(snapshot) {
                var deleteResponseObj = snapshot.val();
            });

            await shopInfoRef.once("value", async function(snapshot) {
                var firebaseResponseObj = snapshot.val();

                await updateInventory.updateInventory(); // do some fetch request to 3rd party API

                await deleteProduct.deleteProduct(); // do another fetch call to 3rd party API

                resolve(); // we put resolve in the very last point of the chain
            });
        });
      });

      await awaiter;
    }
    // terminate the cloud function
    res.end();
}
```

**Comment by nicoleczhu** [comment] 2021-04-05 21:43
Hi @derrickrc I'm guessing you shared the function that doesn't have the client instrumentation yet. Can you initialize error-reporting in this file as well and see what you get?

For writing to stdout, yes you can just do a console.log in a catch statement. Your catch could catch on any exception right? using `uncaughtException' and 'unhandledRejection`

**Comment by derrickrc** [comment] 2021-04-05 23:19
Thanks @nicoleczhu, sorry for the confusion - in my actual file I actually had initialized the client reporting. After playing around with it, I think I've got it. I can simply wrap my entire `index.js` code in `try/catch` and in the `catch(e)` block, if I use `errors.report(e)`, then even if an error occurs in another .js file along the way I will be notified. Is there any danger it to doing it this way?

I think I did experience the race condition you described which is when I throw an exception that actually causes the function to crash, sometimes it doesn't report it and now I understand why.  

One thing I do remain confused about though is, in my testing it seems the only way I can get an error to show up is either a) when an unhandled exception occurs in the main .js file (and the race condition does not occur), or b) using `errors.report()`. When I try using something like `console.error(new Error('I failed you'))` per [this article](https://cloud.google.com/functions/docs/monitoring/error-reporting) I don't get notified or see it in https://console.cloud.google.com/errors. Are these 2 different things?

I also don't think I grasp what's going on with the JSON logging examples you provided and why that's necessary, but that might just be a bit over my head at the moment. Thanks again.

**Comment by nicoleczhu** [comment] 2021-04-05 23:35
great question. So there are 2 ways (minimally) to log/error in cloud functions. 

1. Default approach. When you use the javascript standard library `console` package, i.e. when you type `console.log` `console.error`, it writes your messages to the STDOUT/STDERR stream. This is a very "native" way of writing logs. It will run locally. Then in the Cloud Functions backend, the team actually has custom code that takes these message from your STD stream, parses them, and pings them to the Cloud Logging/Cloud Error Reporting API. There's no race condition here since your console.x commands are a part of your function execution itself. 

I suggest you use this approach. Note you have to [format](https://cloud.google.com/error-reporting/docs/formatting-error-messages#log-entry-examples) the message in console.error(message). 

2. When you use the client libraries, i.e. when you `require('@google-cloud/error-reporting');` and `errors.report()` you are actually bypassing logging to STDOUT/ERR. The nice part is these libraries format your messages for you. Then you are making a sync or asynchronous call to directly write these messages to the Logging/ErrorReporting API. This is why there's a race condition, when your function ramps down but the async api request hasn't been sent.

So your `errors.report` or `console.error` code go in the same place - they are interchangeable, depending on which route you take.

Closing this issue for now as it's not a bug/feature request or question related to this library.

**Closed by nicoleczhu** 2021-04-05 23:35 UTC
Labels: api: clouderrorreporting, priority: p2, triage me, type: question
