### ISSUE TITLE
Does not handle errors thrown by Node's fs module

### ISSUE THREAD

**Issue by rubenvereecken** [googleapis/nodejs-error-reporting#502] opened 2020-07-23 10:53 UTC
#### Environment details

  - Node.js version: v12.2
  - `@google-cloud/error-reporting` version: 2.0.0

#### Steps to reproduce

I found today that not all errors are created equal. I have a very simple setup:

```
		app.use(errorReporting.express)
```

I then tried to test this error reporting. It works with the example in the README which uses `JSON.parse`. I also had my own example which relies on `fs.writeFile`. To my surprise it didn't work.

```
testRouter.post('/error/bug2',
	async (req, res) => {
		await fsPromise.writeFile('/this/is/not/a/path', 'datas', 'utf8');
	});
```
... results in this bad boy
```
ERROR:@google-cloud/error-reporting: Encountered an error while attempting to transmit an error to the Stackdriver Error Reporting API. ApiError: ReportedErrorEvent.context must contain a location unless `message` contain an exception or stacktrace.
```

Now, I can't tell what the `fs` errors are missing that other errors have. For example, upon inspection all the following evaluated to true:
- `err instanceof Error`
- `!!err.message`
- `!!err.stack`

So if it looks like a duck and quacks like a duck... why is it not a duck? The only thing I can think of is that it may have some atypical methods, perhaps a `toJSON` or the like, that make it look all funny when it's being transformed into a request payload. But I'll be honest, this one's beyond me.

```
[Error: ENOENT: no such file or directory, open '/this/is/not/a/path'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/this/is/not/a/path'
}
```

**Comment by laljikanjareeya** [comment] 2020-11-12 11:22
@rubenvereecken I tried with mentioned version, but I could not reproduce it.

The error message that you got is when `context` does not contain a location and `message` also doesn't have any exception or stacktrace.

Here is the complete working example:

```ts
const express = require('express');
const fs = require('fs');

const { ErrorReporting } = require('@google-cloud/error-reporting');

const errors = new ErrorReporting({
    reportMode: 'always'
});

const app = express();

app.post('/error', (req, res, next) => {
    fs.writeFileSync("/this/is/not/a/path", 'datas', 'utf8');
});

app.get('/', (req, res) => {
    res.send('Welcome!!')
});

app.use(errors.express);

app.listen(3000);
```

Output in Cloud Console:

```ts
Error: ENOENT: no such file or directory, open '/this/is/not/a/path'
at Object.openSync (fs.js:462)
at Object.writeFileSync (fs.js:1384)
```

**Comment by nicoleczhu** [comment] 2021-01-21 19:53
Hi @rubenvereecken, can you provide more of your entire code snippet, including how you are reporting the error itself?

Note that your error message needs to be converted into a string.

**Comment by nicoleczhu** [comment] 2021-01-26 23:08
Closing this issue due to 2+ mo no reply. Do feel free to reopen if issue persists.

**Closed by nicoleczhu** 2021-01-26 23:08 UTC
Labels: api: clouderrorreporting, needs more info, priority: p3, type: question
