### ISSUE TITLE
system tests failing on head

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-error-reporting#395] opened 2019-09-13 01:25 UTC
@DominicKramer any thoughts? seems to have started cropping up on a nightly, I haven't taken much time to dig in yet.

**Comment by DominicKramer** [comment] 2019-09-16 16:45
I'm not sure what the error could be caused by.  I've never seen the test that is failing fail before.

**Comment by DominicKramer** [comment] 2019-09-24 20:07
Fixed in PR #400.

**Closed by DominicKramer** 2019-09-24 20:07 UTC
Labels: priority: p1, type: bug
